### ISSUE TITLE
Truncate automatically value according to field size

### ISSUE THREAD

**Issue by edyan** [edyan/neuralyzer#1]
If MySQL is in strict mode, some queries crash because they are trying to enter a bigger value than what is allowed (example : `VARCHAR(80)` and `{ method: sentence, params: [8] }`). 

Before running the query, truncate each value with the field info

**Comment by gsomoza** [comment]
Happened to me too, would be nice to avoid the warning.

**Comment by edyan** [comment]
Should be ok on current dev version.  I'll release a v3 as it's not compatible with the new 2.0 version (manual queries to doctrine dbal).
