### ISSUE TITLE
Problem generating config when having enums in the DB

### ISSUE THREAD

**Issue by bertrandgorge** [edyan/neuralyzer#19]
Hello Emmanuel,

Thanks for this tool. I'm having difficulties to use config:generate because of enums in our DB: 

In AbstractPlatform.php line 454:
  Unknown database type enum requested, Doctrine\DBAL\Platforms\MySQL80Platform may not support it.

Am I doing something wrong?

Thanks !

**Comment by edyan** [comment]
Hi have you tried With the master version ? Else I'll investigate as soon as I can.

**Comment by edyan** [comment]
Hi @bertrandgorge you were right and I have patched the code to allow enum that are not supported by doctrine. The impact is that you have to edit the `neuralyzer.yml` file to set your own enum values. Please try the phar in master or clone master and let me know if it's ok for you ?

Thanks !

**Comment by bertrandgorge** [comment]
Hello @edyan - I'll test that very soon. Thanks a lot for your help!

**Comment by bertrandgorge** [comment]
Hello @edyan - there's definitely an improvement. The error with Enums is now gone, but I'm faced with something new:

```
Unknown column type "phone_number" requested. Any Doctrine type that you use has to be registered with \Doctrine\DB
  AL\Types\Type::addType(). You can get a list of all the known types with \Doctrine\DBAL\Types\Type::getTypesMap().
  If this error occurs during database introspection then you might have forgotten to register all database types for
   a Doctrine Type. Use AbstractPlatform#registerDoctrineTypeMapping() or have your custom types implement Type#getMa
  ppedDatabaseTypes(). If the type name is empty you might have a problem with the cache or forgot some mapping infor
  mation.
```

Apparently, I've imported the DB with Doctrines comments that are interpreted as Doctrine Types. I've got the DB from a Symfony platform :

```sql
CREATE TABLE `adresse` (
  `id` int NOT NULL,
  `rue` varchar(100) DEFAULT NULL COMMENT 'Pour pouvoir effectuer des traitements',
  `numero_rue` varchar(30) DEFAULT NULL COMMENT 'Juste le numéro, pas plus de 30 caractÃ¨res',
  `cp` varchar(10) DEFAULT NULL,
  `ville` varchar(100) DEFAULT NULL,
  `pays` varchar(50) DEFAULT NULL,
  `numero_tel_principal` varchar(35) DEFAULT NULL COMMENT '(DC2Type:phone_number)',
  `numero_tel_secondaire` varchar(35) DEFAULT NULL COMMENT '(DC2Type:phone_number)',
  `complement_adresse` varchar(100) DEFAULT NULL COMMENT 'Etage, Appartement...',
  `mapsLat` varchar(20) DEFAULT NULL,
  `mapsLgt` varchar(20) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

When I remove all comments to get rid of that, it gets a little further, but now fails on JSON types: 

```sql
CREATE TABLE `campagne` (
  `id` int NOT NULL,
  `entite_responsable_id` int DEFAULT NULL,
  `datedebut` datetime NOT NULL,
  `datefin` datetime NOT NULL,
  `titre` varchar(250) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `sommecible` int NOT NULL,
  `formulaire_web` tinyint(1) DEFAULT NULL,
  `formulaire_web_details` json DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

All of that is when I try to `neuralyzer config:generate` - should I skip this step and try to build my config by hand, avoiding those columns ?

Thanks...!

**Comment by edyan** [comment]
That time the problems comes from my code that is unable to define a faker method for a json type field. Also faker has no method to generate a json object. I have then done the following : 
- Created 2 faker methods : `jsonWordsList` and `jsonWordsObject` that will generate a list or an object (Unit tests added)
- Set in the guesser the `jsonWordsObject` for the json field type

I have also corrected a but : 
- the len of a field was not taken into account for a sentence
- the `set` field type wasn't recognized

I have tried with your table + 2 extra fields and it works well :) To make the system more robust, I should add more fields types in my tests :)

Let me know if it's ok for you before I do a release

**Comment by bertrandgorge** [comment]
Hello @edyan - thanks, I'll have a look tonight if I can find the time.

One thing: those issues come from the guesser - which purpose is to create the yaml eventually. But out of this yaml, most of the columns will be removed anyway because they don't _need_ to be anonymised. So it'd be a good thing to just catch the errors when you have them, and dump the yaml anyway, even if there are a few columns that could not be recognised. This is typically the case for json types which might be very hard to anonymise anyway.

Also, it would be great if one could add an anonymization method simply, just by adding the code in some PHP file like bootsrap.php. With access to Faker, a simple method definition that could be called dynamically would help a lot, in the cases where Faker's default routines are not exactly what we need...?

**Comment by edyan** [comment]
hi @bertrandgorge , sorry I didn't see your message earlier. There is away to use a bootstrap.php :) 

Let me know if you have been able to do what you wanted to do

**Comment by bertrandgorge** [comment]
Hello @edyan - to tell you the truth, it was faster and simpler for me to rewrite the script for my own need. I kept the ideas of neuralyzer but I simplified it a lot, and I wrote some specific providers, especially so that I could manage my consistency issues. Thanks !
