### ISSUE TITLE
Feature: How to keep consistency in names ?

### ISSUE THREAD

**Issue by bertrandgorge** [edyan/neuralyzer#20]
Hello,

I'm using neuralizer to anonymize a DB that shall be use for debuging.

One specific of our DB is that we have to tables, lets say `users` and `families`, with a users being part of families.

Both have a last name: usually, Marie Dupond is maried with Jean Dupond, and both are in the same family Dupond. Sometimes there are inconsistencies (divorces, etc...), but that's the idea.

We wondered if there would be a way to use Faker to consistently replace a lastname with another, faked, so that all Dupond would be replaced by the same faked last name...? (in order to keep as much as possible of the relative consistency)

**Comment by edyan** [comment]
Hi, there is no solution to achieve that. That would mean keep in memory potentially a lot of data (Imagine you need to anonymize hundred of thousand of records) and a specific implementation. 

But you have other solutions : 
- You can ignore a field in anonymization. That's not ideal for sure but after doing that, you can have a post_action (see https://github.com/edyan/neuralyzer#pre-and-post-actions) that calls a specific SQL code.
- You can use neuralyzer has a library and do what you want :)
- You can write your own Faker Provider and use your own bootstrap. That's probably the easiest way, from my point of view (https://github.com/edyan/neuralyzer#custom-application-logic) 

Regards
