### ISSUE TITLE
Doctrine does not like bit type column

### ISSUE THREAD

**Issue by bobpattersonjr** [edyan/neuralyzer#6]
I am trying to `generateConfFromDB` and it looks like Doctrine is dying on the bit type column

Stack trace below with a few fields stared out

```
bob@bob:~/neuralyzer$ php test.php
PHP Fatal error:  Uncaught Doctrine\DBAL\DBALException: Unknown database type bit requested, Doctrine\DBAL\Platforms\PostgreSQL92Platform may not support it. in /home/bob/neuralyzer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php:461
Stack trace:
#0 /home/bob/neuralyzer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/PostgreSqlSchemaManager.php(370): Doctrine\DBAL\Platforms\AbstractPlatform->getDoctrineTypeMapping('bit')
#1 /home/bob/neuralyzer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(831): Doctrine\DBAL\Schema\PostgreSqlSchemaManager->_getPortableTableColumnDefinition(Array)
#2 /home/bob/neuralyzer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(186): Doctrine\DBAL\Schema\AbstractSchemaManager->_getPortableTableColumnList('****', '******', Array)
#3 /home/bob/neuralyzer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/AbstractSchemaManager.php(292): Doctrine\DBAL\Schema\AbstractSchemaManager->listTableColumns('****')
#4 /home/bob/neuralyzer/vendor/doctri in /home/bob/neuralyzer/vendor/doctrine/dbal/lib/Doctrine/DBAL/Platforms/AbstractPlatform.php on line 461
```

**Comment by edyan** [comment]
Hi and thanks for the report, it looks like a known problem and people recommend on the web to convert bit fields to booleans. 

https://github.com/doctrine/dbal/issues/1775

Nevertheless I'll look how I can manage it to map the field to boolean even if I use dbal as much as possible to avoid managing specific cases. 

What you can also do is to ignore the field with `setProtectedCols`

**Comment by bobpattersonjr** [comment]
Hi, thanks for getting back to me.

And I have both tried to ignore the column and the table but still get the same error

**Comment by edyan** [comment]
Hi, as doctrine is not able to manage those type of fields, I can't do anything. That crashes at a very high level (I use that method just to get a list of tables and it's where it's blocked : https://www.doctrine-project.org/projects/doctrine-dbal/en/2.7/reference/schema-manager.html#listtables)

It would be better to follow doctrine advice to convert the field or reopen the bug there... sorry for that

**Comment by macropin** [comment]
Doctrine also doesn't seem to handle `enum` - enumerated sets.

**Comment by edyan** [comment]
Hi @macropin  I'll look at that

**Comment by edyan** [comment]
Hi @bobpattersonjr  @macropin  I have updated neuralyzer to partially support enum (config is generated but enum options have to be set manually in config) and bit (replaced by boolean).

Could you test if you have time ? It's the 3.1.1 (https://github.com/edyan/neuralyzer/raw/v3.1.1/neuralyzer.phar)

Thanks
